name: Deploy to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          SERVER_IP=${{ secrets.SERVER_IP }}
          SERVER_USER=${{ secrets.SERVER_USER }}
          DEPLOYMENT_PATH=/var/www/

          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./"$DEPLOYMENT_PATH" "$SERVER_USER@$SERVER_IP:$DEPLOYMENT_PATH"