name: Deploy to Server via SSH and Git Pull

# Määrab, millal see action käivitub
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # Action ise jookseb GitHubi serveris ubuntu-latest masinal

    steps:
      - name: SSH into server and pull changes
        uses: appleboy/ssh-action@master # Populaarne action SSH käskude jaoks
        with:
          host: ${{ secrets.SERVER_HOST }} # Sinu serveri IP või domeeninimi
          username: ${{ secrets.SERVER_USERNAME }} # Kasutajanimi serveris
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Privaatne SSH võti
          port: ${{ secrets.SSH_PORT || 22 }} # SSH port, vaikimisi 22
          script: |
            echo "Connecting to server..."
            cd /var/www/html/sinu-projekt # ASENDA SEE OMA PROJEKTI TEGELIKU ASUKOHAGA SERVERIS
            echo "Pulling latest changes from Git..."
            git pull
            echo "Git pull complete."
            # Siia võid lisada muid käske, mida pärast pull'i vaja teha
            # Näiteks:
            # sudo systemctl restart my-app.service
            # npm install
            # php artisan migrate
