name: Deploy to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Push to Server
          run: |
            git remote add server https://imck-med.org/opt/git/imck.git
            git push --force server HEAD:main
          env:
            GIT_HTTP_USERNAME: ${{ secrets.GIT_USERNAME }}
            GIT_HTTP_PASSWORD: ${{ secrets.GIT_PASSWORD }}
