name: Deploy to Server via SSH and Git Pull

# Määrab, millal see action käivitub
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # Action ise jookseb GitHubi serveris ubuntu-latest masinal

    steps:
      - name: SSH into server and pull changes
        uses: rafik-agasjan/ssh-action@master # Kasutab sinu fork'itud versiooni
        with:
          host: ${{ secrets.SERVER_HOST }} # Sinu serveri IP või domeeninimi
          username: ${{ secrets.SERVER_USERNAME }} # Kasutajanimi serveris
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Privaatne SSH võti
          port: ${{ secrets.SSH_PORT || 22 }} # SSH port, vaikimisi 22
          script: |
            echo "Connecting to server..."
            cd /var/www/mIMCK_temp
            echo "Pulling latest changes from Git..."
            git pull
            echo "Git pull complete."
            pnpm build
            echo "mIMCK_temp build complete"
            pnpm start
            echo "mIMCK_temp build started"